export type WordCategory = '어찌하다' | '어떠하다' | '무엇이다';

export interface Word {
  id: string;
  text: string;
  category: WordCategory;
}

export const WORD_POOL: Word[] = [
  // 어찌하다 (100)
  { id: 'v1', text: '(글을) 쓰다', category: '어찌하다' },
  { id: 'v2', text: '(모자를) 쓰다', category: '어찌하다' },
  { id: 'v3', text: '(돈을) 쓰다', category: '어찌하다' },
  { id: 'v4', text: '달리다', category: '어찌하다' },
  { id: 'v5', text: '먹다', category: '어찌하다' },
  { id: 'v6', text: '자다', category: '어찌하다' },
  { id: 'v7', text: '입다', category: '어찌하다' },
  { id: 'v8', text: '뛰다', category: '어찌하다' },
  { id: 'v9', text: '걷다', category: '어찌하다' },
  { id: 'v10', text: '보다', category: '어찌하다' },
  { id: 'v11', text: '듣다', category: '어찌하다' },
  { id: 'v12', text: '읽다', category: '어찌하다' },
  { id: 'v13', text: '놀다', category: '어찌하다' },
  { id: 'v14', text: '웃다', category: '어찌하다' },
  { id: 'v15', text: '울다', category: '어찌하다' },
  { id: 'v16', text: '타다', category: '어찌하다' },
  { id: 'v17', text: '내리다', category: '어찌하다' },
  { id: 'v18', text: '열다', category: '어찌하다' },
  { id: 'v19', text: '닫다', category: '어찌하다' },
  { id: 'v20', text: '밀다', category: '어찌하다' },
  { id: 'v21', text: '당기다', category: '어찌하다' },
  { id: 'v22', text: '던지다', category: '어찌하다' },
  { id: 'v23', text: '받다', category: '어찌하다' },
  { id: 'v24', text: '차다', category: '어찌하다' },
  { id: 'v25', text: '날다', category: '어찌하다' },
  { id: 'v26', text: '수영하다', category: '어찌하다' },
  { id: 'v27', text: '공부하다', category: '어찌하다' },
  { id: 'v28', text: '노래하다', category: '어찌하다' },
  { id: 'v29', text: '춤추다', category: '어찌하다' },
  { id: 'v30', text: '그리다', category: '어찌하다' },
  { id: 'v31', text: '만들다', category: '어찌하다' },
  { id: 'v32', text: '씻다', category: '어찌하다' },
  { id: 'v33', text: '청소하다', category: '어찌하다' },
  { id: 'v34', text: '마시다', category: '어찌하다' },
  { id: 'v35', text: '가다', category: '어찌하다' },
  { id: 'v36', text: '오다', category: '어찌하다' },
  { id: 'v37', text: '(신발을) 신다', category: '어찌하다' },
  { id: 'v38', text: '(안경을) 쓰다', category: '어찌하다' },
  { id: 'v39', text: '(장갑을) 끼다', category: '어찌하다' },
  { id: 'v40', text: '(양말을) 신다', category: '어찌하다' },
  { id: 'v41', text: '(가방을) 메다', category: '어찌하다' },
  { id: 'v42', text: '(짐을) 들다', category: '어찌하다' },
  { id: 'v43', text: '(문을) 잠그다', category: '어찌하다' },
  { id: 'v44', text: '(불을) 켜다', category: '어찌하다' },
  { id: 'v45', text: '(불을) 끄다', category: '어찌하다' },
  { id: 'v46', text: '(옷을) 벗다', category: '어찌하다' },
  { id: 'v47', text: '(손을) 씻다', category: '어찌하다' },
  { id: 'v48', text: '(세수를) 하다', category: '어찌하다' },
  { id: 'v49', text: '(목욕을) 하다', category: '어찌하다' },
  { id: 'v50', text: '(밥을) 짓다', category: '어찌하다' },
  { id: 'v51', text: '(빵을) 굽다', category: '어찌하다' },
  { id: 'v52', text: '(그림을) 칠하다', category: '어찌하다' },
  { id: 'v53', text: '(종이를) 오리다', category: '어찌하다' },
  { id: 'v54', text: '(풀로) 붙이다', category: '어찌하다' },
  { id: 'v55', text: '(가위로) 자르다', category: '어찌하다' },
  { id: 'v56', text: '(연필을) 깎다', category: '어찌하다' },
  { id: 'v57', text: '(책을) 펴다', category: '어찌하다' },
  { id: 'v58', text: '(책을) 덮다', category: '어찌하다' },
  { id: 'v59', text: '(이름을) 부르다', category: '어찌하다' },
  { id: 'v60', text: '(대답을) 하다', category: '어찌하다' },
  { id: 'v61', text: '(질문을) 하다', category: '어찌하다' },
  { id: 'v62', text: '(인사를) 하다', category: '어찌하다' },
  { id: 'v63', text: '(친구를) 만나다', category: '어찌하다' },
  { id: 'v64', text: '(친구와) 헤어지다', category: '어찌하다' },
  { id: 'v65', text: '(길을) 건너다', category: '어찌하다' },
  { id: 'v66', text: '(산을) 오르다', category: '어찌하다' },
  { id: 'v67', text: '(계단을) 내려가다', category: '어찌하다' },
  { id: 'v68', text: '(버스를) 타다', category: '어찌하다' },
  { id: 'v69', text: '(자전거를) 타다', category: '어찌하다' },
  { id: 'v70', text: '(공을) 던지다', category: '어찌하다' },
  { id: 'v71', text: '(공을) 받다', category: '어찌하다' },
  { id: 'v72', text: '(공을) 차다', category: '어찌하다' },
  { id: 'v73', text: '(줄넘기를) 하다', category: '어찌하다' },
  { id: 'v74', text: '(숨바꼭질을) 하다', category: '어찌하다' },
  { id: 'v75', text: '(술래잡기를) 하다', category: '어찌하다' },
  { id: 'v76', text: '(미끄럼틀을) 타다', category: '어찌하다' },
  { id: 'v77', text: '(그네를) 타다', category: '어찌하다' },
  { id: 'v78', text: '(시소를) 타다', category: '어찌하다' },
  { id: 'v79', text: '(모래성을) 쌓다', category: '어찌하다' },
  { id: 'v80', text: '(구멍을) 파다', category: '어찌하다' },
  { id: 'v81', text: '(씨앗을) 심다', category: '어찌하다' },
  { id: 'v82', text: '(물을) 주다', category: '어찌하다' },
  { id: 'v83', text: '(꽃을) 꺾다', category: '어찌하다' },
  { id: 'v84', text: '(벌레를) 잡다', category: '어찌하다' },
  { id: 'v85', text: '(새를) 쫓다', category: '어찌하다' },
  { id: 'v86', text: '(고양이를) 기르다', category: '어찌하다' },
  { id: 'v87', text: '(강아지를) 산책시키다', category: '어찌하다' },
  { id: 'v88', text: '(밥을) 주다', category: '어찌하다' },
  { id: 'v89', text: '(잠을) 깨다', category: '어찌하다' },
  { id: 'v90', text: '(꿈을) 꾸다', category: '어찌하다' },
  { id: 'v91', text: '(하품을) 하다', category: '어찌하다' },
  { id: 'v92', text: '(기지개를) 켜다', category: '어찌하다' },
  { id: 'v93', text: '(눈을) 비비다', category: '어찌하다' },
  { id: 'v94', text: '(코를) 풀다', category: '어찌하다' },
  { id: 'v95', text: '(기침을) 하다', category: '어찌하다' },
  { id: 'v96', text: '(약을) 먹다', category: '어찌하다' },
  { id: 'v97', text: '(병원을) 가다', category: '어찌하다' },
  { id: 'v98', text: '(주사를) 맞다', category: '어찌하다' },
  { id: 'v99', text: '(울음을) 터뜨리다', category: '어찌하다' },
  { id: 'v100', text: '(눈물을) 닦다', category: '어찌하다' },

  // 어떠하다 (100)
  { id: 'a1', text: '(맛이) 쓰다', category: '어떠하다' },
  { id: 'a2', text: '(입맛이) 쓰다', category: '어떠하다' },
  { id: 'a3', text: '크다', category: '어떠하다' },
  { id: 'a4', text: '작다', category: '어떠하다' },
  { id: 'a5', text: '많다', category: '어떠하다' },
  { id: 'a6', text: '적다', category: '어떠하다' },
  { id: 'a7', text: '높다', category: '어떠하다' },
  { id: 'a8', text: '낮다', category: '어떠하다' },
  { id: 'a9', text: '길다', category: '어떠하다' },
  { id: 'a10', text: '짧다', category: '어떠하다' },
  { id: 'a11', text: '넓다', category: '어떠하다' },
  { id: 'a12', text: '좁다', category: '어떠하다' },
  { id: 'a13', text: '밝다', category: '어떠하다' },
  { id: 'a14', text: '어둡다', category: '어떠하다' },
  { id: 'a15', text: '덥다', category: '어떠하다' },
  { id: 'a16', text: '춥다', category: '어떠하다' },
  { id: 'a17', text: '따뜻하다', category: '어떠하다' },
  { id: 'a18', text: '시원하다', category: '어떠하다' },
  { id: 'a19', text: '무겁다', category: '어떠하다' },
  { id: 'a20', text: '가볍다', category: '어떠하다' },
  { id: 'a21', text: '빠르다', category: '어떠하다' },
  { id: 'a22', text: '느리다', category: '어떠하다' },
  { id: 'a23', text: '예쁘다', category: '어떠하다' },
  { id: 'a24', text: '멋지다', category: '어떠하다' },
  { id: 'a25', text: '귀엽다', category: '어떠하다' },
  { id: 'a26', text: '밉다', category: '어떠하다' },
  { id: 'a27', text: '좋다', category: '어떠하다' },
  { id: 'a28', text: '나쁘다', category: '어떠하다' },
  { id: 'a29', text: '기쁘다', category: '어떠하다' },
  { id: 'a30', text: '슬프다', category: '어떠하다' },
  { id: 'a31', text: '아프다', category: '어떠하다' },
  { id: 'a32', text: '건강하다', category: '어떠하다' },
  { id: 'a33', text: '조용하다', category: '어떠하다' },
  { id: 'a34', text: '시끄럽다', category: '어떠하다' },
  { id: 'a35', text: '깨끗하다', category: '어떠하다' },
  { id: 'a36', text: '더럽다', category: '어떠하다' },
  { id: 'a37', text: '맑다', category: '어떠하다' },
  { id: 'a38', text: '흐리다', category: '어떠하다' },
  { id: 'a39', text: '달다', category: '어떠하다' },
  { id: 'a40', text: '짜다', category: '어떠하다' },
  { id: 'a41', text: '시다', category: '어떠하다' },
  { id: 'a42', text: '맵다', category: '어떠하다' },
  { id: 'a43', text: '싱겁다', category: '어떠하다' },
  { id: 'a44', text: '고소하다', category: '어떠하다' },
  { id: 'a45', text: '쓰디쓰다', category: '어떠하다' },
  { id: 'a46', text: '부드럽다', category: '어떠하다' },
  { id: 'a47', text: '딱딱하다', category: '어떠하다' },
  { id: 'a48', text: '말랑말랑하다', category: '어떠하다' },
  { id: 'a49', text: '거칠다', category: '어떠하다' },
  { id: 'a50', text: '매끄럽다', category: '어떠하다' },
  { id: 'a51', text: '둥글다', category: '어떠하다' },
  { id: 'a52', text: '네모나다', category: '어떠하다' },
  { id: 'a53', text: '세모나다', category: '어떠하다' },
  { id: 'a54', text: '뾰족하다', category: '어떠하다' },
  { id: 'a55', text: '뭉툭하다', category: '어떠하다' },
  { id: 'a56', text: '두껍다', category: '어떠하다' },
  { id: 'a57', text: '얇다', category: '어떠하다' },
  { id: 'a58', text: '굵다', category: '어떠하다' },
  { id: 'a59', text: '가늘다', category: '어떠하다' },
  { id: 'a60', text: '깊다', category: '어떠하다' },
  { id: 'a61', text: '얕다', category: '어떠하다' },
  { id: 'a62', text: '뜨겁다', category: '어떠하다' },
  { id: 'a63', text: '차갑다', category: '어떠하다' },
  { id: 'a64', text: '미지근하다', category: '어떠하다' },
  { id: 'a65', text: '서늘하다', category: '어떠하다' },
  { id: 'a66', text: '쌀쌀하다', category: '어떠하다' },
  { id: 'a67', text: '포근하다', category: '어떠하다' },
  { id: 'a68', text: '눈부시다', category: '어떠하다' },
  { id: 'a69', text: '깜깜하다', category: '어떠하다' },
  { id: 'a70', text: '희다', category: '어떠하다' },
  { id: 'a71', text: '검다', category: '어떠하다' },
  { id: 'a72', text: '붉다', category: '어떠하다' },
  { id: 'a73', text: '푸르다', category: '어떠하다' },
  { id: 'a74', text: '노랗다', category: '어떠하다' },
  { id: 'a75', text: '파랗다', category: '어떠하다' },
  { id: 'a76', text: '까맣다', category: '어떠하다' },
  { id: 'a77', text: '하얗다', category: '어떠하다' },
  { id: 'a78', text: '빨갛다', category: '어떠하다' },
  { id: 'a79', text: '동그랗다', category: '어떠하다' },
  { id: 'a80', text: '길쭉하다', category: '어떠하다' },
  { id: 'a81', text: '납작하다', category: '어떠하다' },
  { id: 'a82', text: '통통하다', category: '어떠하다' },
  { id: 'a83', text: '홀쭉하다', category: '어떠하다' },
  { id: 'a84', text: '뚱뚱하다', category: '어떠하다' },
  { id: 'a85', text: '날씬하다', category: '어떠하다' },
  { id: 'a86', text: '튼튼하다', category: '어떠하다' },
  { id: 'a87', text: '약하다', category: '어떠하다' },
  { id: 'a88', text: '똑똑하다', category: '어떠하다' },
  { id: 'a89', text: '어리석다', category: '어떠하다' },
  { id: 'a90', text: '착하다', category: '어떠하다' },
  { id: 'a91', text: '악하다', category: '어떠하다' },
  { id: 'a92', text: '부지런하다', category: '어떠하다' },
  { id: 'a93', text: '게으르다', category: '어떠하다' },
  { id: 'a94', text: '용감하다', category: '어떠하다' },
  { id: 'a95', text: '겁나다', category: '어떠하다' },
  { id: 'a96', text: '무섭다', category: '어떠하다' },
  { id: 'a97', text: '두렵다', category: '어떠하다' },
  { id: 'a98', text: '반갑다', category: '어떠하다' },
  { id: 'a99', text: '아쉽다', category: '어떠하다' },
  { id: 'a100', text: '그립다', category: '어떠하다' },

  // 무엇이다 (100)
  { id: 'n1', text: '학생이다', category: '무엇이다' },
  { id: 'n2', text: '선생님이다', category: '무엇이다' },
  { id: 'n3', text: '학교다', category: '무엇이다' },
  { id: 'n4', text: '책상이다', category: '무엇이다' },
  { id: 'n5', text: '의자다', category: '무엇이다' },
  { id: 'n6', text: '연필이다', category: '무엇이다' },
  { id: 'n7', text: '지우개다', category: '무엇이다' },
  { id: 'n8', text: '가방이다', category: '무엇이다' },
  { id: 'n9', text: '책이다', category: '무엇이다' },
  { id: 'n10', text: '공책이다', category: '무엇이다' },
  { id: 'n11', text: '컴퓨터다', category: '무엇이다' },
  { id: 'n12', text: '칠판이다', category: '무엇이다' },
  { id: 'n13', text: '시계다', category: '무엇이다' },
  { id: 'n14', text: '창문이다', category: '무엇이다' },
  { id: 'n15', text: '문이다', category: '무엇이다' },
  { id: 'n16', text: '피아노다', category: '무엇이다' },
  { id: 'n17', text: '축구공이다', category: '무엇이다' },
  { id: 'n18', text: '자전거다', category: '무엇이다' },
  { id: 'n19', text: '자동차다', category: '무엇이다' },
  { id: 'n20', text: '비행기다', category: '무엇이다' },
  { id: 'n21', text: '기차다', category: '무엇이다' },
  { id: 'n22', text: '배다', category: '무엇이다' },
  { id: 'n23', text: '사과다', category: '무엇이다' },
  { id: 'n24', text: '바나나다', category: '무엇이다' },
  { id: 'n25', text: '포도다', category: '무엇이다' },
  { id: 'n26', text: '수박이다', category: '무엇이다' },
  { id: 'n27', text: '강아지다', category: '무엇이다' },
  { id: 'n28', text: '고양이다', category: '무엇이다' },
  { id: 'n29', text: '토끼다', category: '무엇이다' },
  { id: 'n30', text: '사자다', category: '무엇이다' },
  { id: 'n31', text: '호랑이다', category: '무엇이다' },
  { id: 'n32', text: '코끼리다', category: '무엇이다' },
  { id: 'n33', text: '기린이다', category: '무엇이다' },
  { id: 'n34', text: '원숭이다', category: '무엇이다' },
  { id: 'n35', text: '곰이다', category: '무엇이다' },
  { id: 'n36', text: '돼지다', category: '무엇이다' },
  { id: 'n37', text: '소다', category: '무엇이다' },
  { id: 'n38', text: '말이다', category: '무엇이다' },
  { id: 'n39', text: '양이다', category: '무엇이다' },
  { id: 'n40', text: '염소다', category: '무엇이다' },
  { id: 'n41', text: '닭이다', category: '무엇이다' },
  { id: 'n42', text: '오리다', category: '무엇이다' },
  { id: 'n43', text: '참새다', category: '무엇이다' },
  { id: 'n44', text: '비둘기다', category: '무엇이다' },
  { id: 'n45', text: '까치다', category: '무엇이다' },
  { id: 'n46', text: '까마귀다', category: '무엇이다' },
  { id: 'n47', text: '물고기다', category: '무엇이다' },
  { id: 'n48', text: '상어다', category: '무엇이다' },
  { id: 'n49', text: '고래다', category: '무엇이다' },
  { id: 'n50', text: '거북이다', category: '무엇이다' },
  { id: 'n51', text: '개구리다', category: '무엇이다' },
  { id: 'n52', text: '뱀이다', category: '무엇이다' },
  { id: 'n53', text: '나비다', category: '무엇이다' },
  { id: 'n54', text: '벌이다', category: '무엇이다' },
  { id: 'n55', text: '개미다', category: '무엇이다' },
  { id: 'n56', text: '거미다', category: '무엇이다' },
  { id: 'n57', text: '모기다', category: '무엇이다' },
  { id: 'n58', text: '파리다', category: '무엇이다' },
  { id: 'n59', text: '잠자리다', category: '무엇이다' },
  { id: 'n60', text: '매미다', category: '무엇이다' },
  { id: 'n61', text: '무당벌레다', category: '무엇이다' },
  { id: 'n62', text: '달팽이다', category: '무엇이다' },
  { id: 'n63', text: '지렁이다', category: '무엇이다' },
  { id: 'n64', text: '나무다', category: '무엇이다' },
  { id: 'n65', text: '꽃이다', category: '무엇이다' },
  { id: 'n66', text: '풀이다', category: '무엇이다' },
  { id: 'n67', text: '잎이다', category: '무엇이다' },
  { id: 'n68', text: '뿌리다', category: '무엇이다' },
  { id: 'n69', text: '열매다', category: '무엇이다' },
  { id: 'n70', text: '씨앗이다', category: '무엇이다' },
  { id: 'n71', text: '돌이다', category: '무엇이다' },
  { id: 'n72', text: '흙이다', category: '무엇이다' },
  { id: 'n73', text: '모래다', category: '무엇이다' },
  { id: 'n74', text: '물이다', category: '무엇이다' },
  { id: 'n75', text: '불이다', category: '무엇이다' },
  { id: 'n76', text: '바람이다', category: '무엇이다' },
  { id: 'n77', text: '구름이다', category: '무엇이다' },
  { id: 'n78', text: '비다', category: '무엇이다' },
  { id: 'n79', text: '눈이다', category: '무엇이다' },
  { id: 'n80', text: '얼음이다', category: '무엇이다' },
  { id: 'n81', text: '해다', category: '무엇이다' },
  { id: 'n82', text: '달이다', category: '무엇이다' },
  { id: 'n83', text: '별이다', category: '무엇이다' },
  { id: 'n84', text: '하늘이다', category: '무엇이다' },
  { id: 'n85', text: '땅이다', category: '무엇이다' },
  { id: 'n86', text: '바다다', category: '무엇이다' },
  { id: 'n87', text: '강이다', category: '무엇이다' },
  { id: 'n88', text: '산이다', category: '무엇이다' },
  { id: 'n89', text: '들이다', category: '무엇이다' },
  { id: 'n90', text: '숲이다', category: '무엇이다' },
  { id: 'n91', text: '길이다', category: '무엇이다' },
  { id: 'n92', text: '집이다', category: '무엇이다' },
  { id: 'n93', text: '방이다', category: '무엇이다' },
  { id: 'n94', text: '거실이다', category: '무엇이다' },
  { id: 'n95', text: '부엌이다', category: '무엇이다' },
  { id: 'n96', text: '화장실이다', category: '무엇이다' },
  { id: 'n97', text: '마당이다', category: '무엇이다' },
  { id: 'n98', text: '지붕이다', category: '무엇이다' },
  { id: 'n99', text: '벽이다', category: '무엇이다' },
  { id: 'n100', text: '바닥이다', category: '무엇이다' },
];
